### ISSUE TITLE
No data loaded when running with Docker

### ISSUE THREAD

**Issue by brianmmcgrath** [DanWahlin/Angular-RESTfulService#12]
No seed data loaded when running with Docker (mac).  Both mongo and nodeapp appear to be running successfully but no db entries displayed, nor am I able to add new entries.  Terminal output snippet:

`mongodb    | 2017-10-01T01:31:36.148+0000 I INDEX    [conn1] build index on: 
customermanager.customers properties: { v: 2, key: { id: 1, type: 1 }, name: "id_1_type_1", ns: 
customermanager.customers", background: true }
mongodb    | 2017-10-01T01:31:36.150+0000 I INDEX    [conn1] build index done.  scanned 0 total 
records. 0 secs
nodeapp    | *** customers
nodeapp    | *** accessDB.getCustomers
nodeapp    | Customers count: 0
nodeapp    | *** customers ok
nodeapp    | *** customers
nodeapp    | *** accessDB.getCustomers`

**Comment by DanWahlin** [comment]
Thanks for letting me know. I'm seeing that same behavior now too (odd since it was working fine less than a month ago). I'm guessing either a package update or something with Docker changed. Once I have time to look into it more I'll let you know what I find. Hoping "docker logs" will have more details.

**Comment by DanWahlin** [comment]
Give the latest version a try now. Looks like there is a breaking change in the latest mongoose version related to the connection (had to add a new useMongoClient property). Works locally and in Docker for me now.

**Comment by brianmmcgrath** [comment]
Awesome, thanks Dan, working now.
