### ISSUE TITLE
unable to launch the application Win10

### ISSUE THREAD

**Issue by saro199** [DanWahlin/Angular-RESTfulService#13]
I was able to start the app using npm start, and DB seeder loads and everything good, 
When launching the application in chrome browser the
Index.html is not able to identify the following js files and it stays in loading in chrome browser

    <script src="lib/shim.min.js"></script>
    <script src="lib/zone.js"></script>
    <script src="lib/system.src.js"></script>
    <script src="systemjs.config.js"></script>
    <script>
      System.import('app').catch(function(err){ console.error(err); });
    </script>

Following is the error in chrome console.

shim.min.js:1 Uncaught SyntaxError: Unexpected token <
zone.js:1 Uncaught SyntaxError: Unexpected token <
system.src.js:1 Uncaught SyntaxError: Unexpected token <
systemjs.config.js:50 Uncaught ReferenceError: System is not defined
    at systemjs.config.js:50
    at systemjs.config.js:61
(anonymous) @ systemjs.config.js:50
(anonymous) @ systemjs.config.js:61
(index):22 Uncaught ReferenceError: System is not defined
    at (index):22
(anonymous) @ (index):22

**Comment by DanWahlin** [comment]
Are you running a different project maybe? The code you show isn't from this project. This project references the scripts from node_modules in index.html and doesn't have a "lib" folder. Some other projects I have do use "lib" folder like you show but you have to run a gulp command to get the scripts in place.  

If you meant to post this in another project make sure you've followed all of the steps in the readme for the project - namely running the gulp command. But, this project doesn't require that step as mentioned.

**Comment by saro199** [comment]
Hi Dan,

I am sorry it was on different project on your git, I got the source after going over the plural sight 
angular-nodejs-restful-services/exercise-files. I have created the issue on the other project, I have followed the readme instruction but no luck, by the way I am really new to Angular, Node and Mongoose.
