### ISSUE TITLE
Unable to save

### ISSUE THREAD

**Issue by tej-rana** [DanWahlin/Angular-RESTfulService#6]
![edit_fail](https://cloud.githubusercontent.com/assets/1436681/18857989/e32f8428-84ab-11e6-9ad9-b0ee39eb7866.PNG)

As you can see from the image, edit is failing. This has nothing to do with what you have in the course but I thought you might want to clean this up.

**Comment by DanWahlin** [comment]
Thanks for the screenshot. I just ran it on Mac and Windows successfully without an error. There was a problem but it's been fixed as far as I'm aware for quite awhile. Do you have the latest version of the code?

**Comment by tej-rana** [comment]
Well  I do and I don't. Proxy is preventing me a clone (although I'm using fiddler to pull npm packages). So I pretty much copy pasted from the browser. Perhaps I've missed something. I've gone through all your videos and quite enjoyed them. I'm going to close it. I suspect it is a copy paste thing. If you get another user complaining then perhaps there is something? But you mention being able to run. So that's probably mongodb.

**Comment by DanWahlin** [comment]
I've run it directly on a machine (without Docker) and with Docker and am not able to replicate that issue. If you can get the latest code downloaded as a .zip or cloned let me know if you still see the issue though. Thanks!
