### ISSUE TITLE
Loading Mongo Data Doesn't work

### ISSUE THREAD

**Issue by slashbrackets** [DanWahlin/Angular-RESTfulService#7]
Not sure how the data gets loaded per the instructions on the readme page. I don't see anywhere data is being imported. I've tried localhost in the config as well. No joy.

**Comment by DanWahlin** [comment]
It's loaded on Line 38 of server.js. If you're not running the application with Docker make sure that your NODE_ENV environment variable is set to "development". I suspect that's probably the issue. I'm going to change it so it always runs the seeder regardless of the value though just in case anyone else runs into that....wouldn't be good for production, but this is just a prototype app.
